---
- hosts: packstack
  become: yes
  become_method: sudo
  gather_facts: true

  tasks:
  - name: "Disable firewalld and NetworkManager."
    service: name={{item}} state=stopped enabled=no  
    with_items:
      - "firewalld"
      - "NetworkManager"  
 
  - name: "Disable SELinux"
    selinux:
      policy: targeted
      state: permissive
  
  - name: "Installing Network-scripts"
    dnf:
      name: "network-scripts"
      state: present

  - name: "Enabling Network"
    systemd:
      name: network
      enabled: yes
  
  - name: "Garantee PowerTools repository enabled"
    command: dnf config-manager --enable PowerTools
  
  - name: "Garantee EPEL repository disabled"
    command: dnf config-manager --disable epel epel-modular
 
  - name: "Install repository packages for OpenStack"
    package:
      name: "{{item}}"
      state: present
    with_items:
      - "centos-release-openstack-train"
      - "vim"
    register: result

  - name: "Updating packages"
    command: dnf update -y --exclude=kernel*
    when: result is success
  
  - name: "Installling OpenStack-Packstack package"
    dnf: 
      name: openstack-packstack
      state: present
    when: result is  success

  - name: "Copying PackStack Answers file"
    copy:
      src: "{{playbook_dir}}/packstack-answers.txt"
      dest: /tmp/packstack-answers.txt

  - name: "Installing packstack with --answer-file option"
    command: packstack --answer-file /tmp/packstack-answers.txt
    when: result is success
               
               
               
